# 开发环境配置
spring:
  mail:
    host: smtp.163.com
    username: lzk199504272024@163.com
    password: UCKXKKHQCLHUTDNE
    port: 465
    properties:
      from: lzk199504272024@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  security:
    jwt:
      key: abcdefghijklmnopqrstuvwxyz
      expire: 7
    filter:
      order: -100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.55.86.138:3306/study?useUnicode=true&characterEncoding=UTF-8
    username: test
    password: 123456
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6001
  rabbitmq:
    addresses: 114.55.86.138
    username: admin
    password: 123456
    virtual-host: /test
  web:
    verify:
      mail-limit: 60
logging:
  level:
    root: info