spring:
  security:
    jwt:
      key: abcdefghijklmnopqrstuvwxyz
      expire: 7
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.55.86.138:3306/study?useUnicode=true&characterEncoding=UTF-8
    username: test
    password: 123456
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6001

logging:
  level:
    root: info
